global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: nginx-ingress
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['nginx-ingress-controller.ingress-nginx.svc.cluster.local:10254']

  - job_name: duss-webapp-svc
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: duss-webapp-svc
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: "5000"
  
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost: 9090
