# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rental_app.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rental_app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rental_app.proto\"\x1f\n\x0b\x62irthdayMsg\x12\x10\n\x08\x62irthday\x18\x01 \x01(\x03\"i\n\x06\x64inMsg\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0e\n\x06h_unit\x18\x03 \x01(\x05\x12\x0e\n\x06weight\x18\x04 \x01(\x05\x12\x0e\n\x06w_unit\x18\x05 \x01(\x05\x12\x12\n\nskier_type\x18\x06 \x01(\x05\"A\n\x08totalMsg\x12\x0f\n\x07\x65q_type\x18\x01 \x01(\x05\x12\x12\n\nlease_type\x18\x02 \x01(\x05\x12\x10\n\x08pkg_type\x18\x03 \x01(\x05\"\x17\n\x08\x61geReply\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\"\x17\n\x08\x64inReply\x12\x0b\n\x03\x64in\x18\x01 \x01(\x02\"\x1b\n\ntotalReply\x12\r\n\x05total\x18\x01 \x01(\x02\x32\'\n\x03\x61ge\x12 \n\x03\x61ge\x12\x0c.birthdayMsg\x1a\t.ageReply\"\x00\x32\"\n\x03\x64in\x12\x1b\n\x03\x64in\x12\x07.dinMsg\x1a\t.dinReply\"\x00\x32*\n\x05total\x12!\n\x05total\x12\t.totalMsg\x1a\x0b.totalReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rental_app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIRTHDAYMSG']._serialized_start=20
  _globals['_BIRTHDAYMSG']._serialized_end=51
  _globals['_DINMSG']._serialized_start=53
  _globals['_DINMSG']._serialized_end=158
  _globals['_TOTALMSG']._serialized_start=160
  _globals['_TOTALMSG']._serialized_end=225
  _globals['_AGEREPLY']._serialized_start=227
  _globals['_AGEREPLY']._serialized_end=250
  _globals['_DINREPLY']._serialized_start=252
  _globals['_DINREPLY']._serialized_end=275
  _globals['_TOTALREPLY']._serialized_start=277
  _globals['_TOTALREPLY']._serialized_end=304
  _globals['_AGE']._serialized_start=306
  _globals['_AGE']._serialized_end=345
  _globals['_DIN']._serialized_start=347
  _globals['_DIN']._serialized_end=381
  _globals['_TOTAL']._serialized_start=383
  _globals['_TOTAL']._serialized_end=425
# @@protoc_insertion_point(module_scope)
