apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-rental-server
  labels:
    app: grpc-rental-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-rental-server
  template:
    metadata:
      labels:
        app: grpc-rental-server
    spec:
      containers:
      - name: grpc-rental-server
        image: doga4097/grpc_rental_server:latest
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-rental-server-svc
  labels:
    app: grpc-rental-server
spec:
  selector:
    app: grpc-rental-server
  ports:
  - protocol: "TCP"
    port: 50051
    targetPort: 50051